#See https://github.com/zricethezav/gitleaks#configuration

title = "Foundry Template"

[extend]
useDefault = true

[[rules]]
id = "ethereum-rule-1"
description = "Ethereum private keys"
regex = '''(?:\'|"|\s|^)(?:0x)?[a-fA-F0-9]{64}(?:\'|"|\s|;|$)'''


[allowlist]
paths = [
    '''lib/(.*?)''',
    '''out/(.*?)''',
    '''bin/(.*?)''',
    '''broadcast/(.*?)''',
    '''cache/(.*?)''',
    '''artifacts/(.*?)''',
    '''node_modules/(.*?)''',
    '''test/utils/Addresses.sol''',
    '''test/oracles/providers/TellorOracle.t.sol''',
    '''test/pricing/TellorValueProvider.t.sol''',
    '''test/utils/ReadPlan.sol''',
    '''src/solver/VM.sol''',
    '''solver/test/Adapters.test.ts''',
    '''solver/test/payloads/adapters/(.*?)''',
    '''solver/README.md''',
]

regexTarget = "match"
regexes = ['''0x[a-fA-F0-9]{40}[\s'";,\W]+''']
